id: config_3  # Automatically created id
icon: mdi:settings
title: Config
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: glance
            title: Settings
            columns: 3
            entities:
              - entity: input_boolean.on_holiday
                name: Holiday
              - entity: input_boolean.guest_mode
                name: Guests?
              - entity: input_boolean.tv_movie_lights
                name: Movie lights
      - type: horizontal-stack
        cards:
          - type: glance
            title: Misc
            columns: 2
            entities:
              - entity: binary_sensor.workday_sensor
                name: Workday
              - entity: light.gateway_light
                name: Alarm light

  #Wine Fridge
  - id: 23987927924khjh343494937493749  # Automatically created id
    type: glance
    title: Wine Fridge
    columns: 5
    entities:
      - entity: input_boolean.winefridge_off_night
        name: Auto Off?
      - entity: switch.lumi_winefridge
        name: WineFridge
      - entity: sensor.lumi_temperature_winefridge
        name: Temperature
      - entity: sensor.lumi_humidity_winefridge
        name: Humidity
      - entity: sensor.lumi_winefridge_current_power
        name: watt
    style: |
      ha-card {
        background: url(http://www.hotelsienaborgogrondaie.com/sienahotelstuscany-2016/wp-content/uploads/2014/03/1937_vino_03-e1496502091807.jpg);
        --primary-text-color: rgb(255,255,255);
        --paper-listbox-background-color: black;
        text-shadow: 1px 1px 0 #000;
      }


  #DNS
  - id: 1bd4ca45036648d5a224aed814e4ad72  # Automatically created id
    type: entities
    title: DNS & IP Address
    show_header_toggle: false
    entities:
      - sensor.dns_domain_resolver
      - sensor.myip

  #Internet
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            title: Internet
            show_header_toggle: false
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_upload
              - sensor.speedtest_ping
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_download
            name: Download
          - entity: sensor.speedtest_upload
            name: upload
        points_per_hour: 1
        height: 200
        hours_to_show: 240
        animate: true
        name: Internet
        show:
          name: true
          icon: false
          points: false
          legend: true
          extrema: false
          labels: true

  - type: custom:vertical-stack-in-card
    cards:
      - type: markdown
        content: >
          #### NZB
      - type: horizontal-stack
        cards:
          - type: glance
            column_width: 33%
            entities:
              - entity: sensor.nzbget_speed
                name: Current Speed
              - entity: sensor.nzbget_queue_size
                name: Queue
          - type: "custom:button-card"
            template: sensor
            entity: sensor.nzbget_download_paused
            name: Toggle 
            show_state: false
            show_last_changed: false
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.nzb_toggle
            state:
              - value: 'True'
                icon: mdi:download-off
                label: 'Paused'
              - operator: 'default'
                icon: mdi:download
                label: 'Downloading'
                styles:
                  icon:
                    - filter: opacity(50%) 

          

  #Proximity
  - id: cb32c2a37a334ebcab2000c212014f11  # Automatically created id
    type: entities
    title: Proximity
    show_header_toggle: false
    entities:
      - device_tracker.nicsiphone7
      - device_tracker.ullisiphone
      - proximity.home_ulli
      - proximity.home_nic

  #Fuel
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: fuel
            entity: sensor.united_petroleum_dee_why_e10
            name: E10
          - type: "custom:button-card"
            template: fuel
            entity: sensor.united_petroleum_dee_why_u91
            name: U 91
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.united_petroleum_dee_why_e10
            name: E10
          - entity: sensor.united_petroleum_dee_why_u91
            name: U91
        points_per_hour: .20
        hours_to_show: 240
        animate: true
        show:
          name: false
          icon: false
          points: false
          legend: true
          extrema: false
          labels: true

  
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.espresso_current_power
        name: Espresso
      - entity: sensor.mediaunit_current_power
        name: Media Unit
      - entity: sensor.lumi_winefridge_current_power
        name: Winefridge
    points_per_hour: 1
    height: 200
    hours_to_show: 240
    animate: true
    name: Smart Plugs
    show:
      name: true
      icon: false
      points: false
      legend: true
      extrema: false
      labels: true
  

  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.bibop
    map_image: '/local/vacuum_map.jpeg'
    debug: false
    calibration_points:
      - vacuum:    #bedroom door point
          x: 22330
          y: 25500
        map:
          x: 405    
          y: 295    
      - vacuum:    #hallway point
          x: 19600
          y: 25500
        map:
          x: 270
          y: 295    
      - vacuum:   #dining point
          x: 19600
          y: 30300
        map:
          x: 270
          y: 40    
    zones:
      - [[20625, 24717, 21650, 22800]] 
      - [[14340, 25054, 17926, 27791]]
      - [[22316, 30491, 18691, 28129]]
      - [[18691, 28129, 22236, 24904]]
      - [[22357, 25879, 26465, 22167]]
      - [[18933, 22955, 17080, 24679], [19014, 24604, 18087, 25804]]
      - [[15147, 24717, 16919, 22955]]
      - [[26707, 22505, 28560, 23817]]
