id: config_3  # Automatically created id
icon: mdi:settings
title: Config
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: fuel_and_download
            entity: input_boolean.on_holiday
            name: Holiday 
          - type: custom:button-card
            template: fuel_and_download
            entity: input_boolean.guest_mode
            name: Guests? 
          - type: custom:button-card
            template: fuel_and_download
            entity: light.gateway_light
            name: Alarm light
          - type: custom:button-card
            template: fuel_and_download
            entity: binary_sensor.workday_sensor
            name: Work day?
            show_state: false
            state:
              - value: "on"
                icon: mdi:briefcase-outline
                label: 'Yupp'
              - value: "off"
                icon: mdi:palm-tree
                label: 'Nope!'



  #Wine Fridge
  - id: 23987927924khjh343494937493749  # Automatically created id
    type: glance
    title: Wine Fridge
    columns: 4
    entities:
      - entity: switch.plug_158_winefridge
        name: Fridge
      - entity: sensor.158_temperature_winefridge
        name: Temp
      - entity: sensor.158_humidity_winefridge
        name: Humidity
      - entity: sensor.plug_158_winefridge_current_power 
        name: watt
    style: |
      ha-card {
        background: url(http://www.hotelsienaborgogrondaie.com/sienahotelstuscany-2016/wp-content/uploads/2014/03/1937_vino_03-e1496502091807.jpg);
        --primary-text-color: rgb(255,255,255);
        --paper-listbox-background-color: black;
        text-shadow: 1px 1px 0 #000;
        background-color: rgba(0, 0, 0, 0);
      }


  #DNS
  - id: 1bd4ca45036648d5a224aed814e4ad72  # Automatically created id
    type: entities
    title: DNS & IP Address
    show_header_toggle: false
    entities:
      - entity: sensor.myip
        name: external IP
      - entity: sensor.dns_domain_resolver
        name: family
      - sensor.ulnic

  #Internet
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            title: Internet
            show_header_toggle: false
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_upload
              - sensor.speedtest_ping
            style: |
              ha-card {
                margin-right: 5px;
                margin-bottom: 5px;
                background-color: rgba(0, 0, 0, 0);
                -webkit-box-shadow: none;
                -moz-box-shadow: none;
                box-shadow: none;
              }
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_download
            name: Download
          - entity: sensor.speedtest_upload
            name: upload
        points_per_hour: 1
        height: 200
        hours_to_show: 240
        animate: true
        line_width: 2
        show:
          name: false
          icon: false
          points: false
          legend: true
          extrema: false
          labels: true
          state: false
        style: |
          ha-card {
            margin-right: 5px;
            margin-bottom: 5px;
            background-color: rgba(0, 0, 0, 0);
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
          }

  - type: custom:vertical-stack-in-card
    cards:
      - type: markdown
        content: >
          #### NZB
        style: |
          ha-card {
            background-color: rgba(0, 0, 0, 0);
          }
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: fuel_and_download
            entity: sensor.nzbget_speed
            icon: mdi:cloud-download-outline
            name: DL Speed 
          - type: custom:button-card
            template: fuel_and_download
            entity: sensor.nzbget_queue_size
            icon: mdi:tray-full
            name: Queue 
          - type: custom:button-card
            template: nzb
            entity: sensor.nzbget_download_paused
            name: Toggle 


  #Proximity
  - type: entities
    title: Proximity
    show_header_toggle: false
    entities:
      - person.nic
      - person.ulli
      - proximity.home_ulli
      - proximity.home_nic

  #Fuel
  - type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: fuel_and_download
            entity: sensor.united_petroleum_dee_why_e10
            name: E10
          - type: "custom:button-card"
            template: fuel_and_download
            entity: sensor.united_petroleum_dee_why_u91
            name: U 91
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.united_petroleum_dee_why_e10
            name: E10
          - entity: sensor.united_petroleum_dee_why_u91
            name: U91
        points_per_hour: .20
        hours_to_show: 240
        animate: true
        line_width: 2
        show:
          name: false
          icon: false
          points: false
          legend: true
          extrema: false
          labels: true
          state: false
        style: |
          ha-card {
            margin-right: 5px;
            margin-bottom: 5px;
            background-color: rgba(0, 0, 0, 0);
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
          }

  
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.espresso_current_power
        name: Espresso
      - entity: sensor.mediaunit_current_power
        name: Media Unit
      - entity: sensor.plug_158_winefridge_current_power
        name: Winefridge
    points_per_hour: 1
    height: 200
    hours_to_show: 240
    animate: true
    name: Smart Plugs
    line_width: 2
    show:
      name: true
      icon: false
      points: false
      legend: true
      extrema: false
      labels: true
    style: |
      ha-card {
        margin-right: 5px;
        margin-bottom: 5px;
        background-color: rgba(0, 0, 0, 0.5);
        -webkit-box-shadow: none;
        -moz-box-shadow: none;
        box-shadow: none;
      }

  - type: custom:mini-graph-card
    entities:
      - entity: sensor.withings_weight_kg_nic
        name: Weight kg
      - entity: sensor.withings_fat_ratio_pct_nic
        name: Fat %
        y_axis: secondary
    points_per_hour: 1
    height: 200
    hours_to_show: 720
    animate: true
    line_width: 2
    name: Weight
    show:
      name: true
      icon: true
      points: false
      legend: true
      extrema: false
      labels: true
