homeassistant:

  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
  auth_mfa_modules:
    - type: totp
      name: Authenticator app
    - type: notify
      message: 'I almost forget, to get into my clubhouse, you need to say {}'

http: !include 1-file-config/http.yaml
sun:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Enables the frontend
frontend: 
  javascript_version: latest
  themes: !include_dir_merge_named themes
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend
conversation:
# Checks for available updates
updater:
  reporting: yes
# Set recorder options
recorder: !include 1-file-config/recorder.yaml
map:
config:
system_health:
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    lovelace-floorplan-yaml: # Needs to contain a hyphen (-)
      mode: yaml
      filename: lovelace-floorplan.yaml
      title: Floorplan
      icon: mdi:floor-plan
      show_in_sidebar: true
      require_admin: true
    guestmode-yaml: # Needs to contain a hyphen (-)
      mode: yaml
      filename: lovelace-guestmode.yaml
      title: GuestMode
      icon: mdi:account-group
      show_in_sidebar: true
      require_admin: false

person:
mobile_app:
ssdp:
zeroconf:
notify:
  - name: all_ios
    platform: group
    services:
      - service: mobile_app_nicsiphone
      - service: mobile_app_ulli_s_iphonese

################################################
## Test
################################################
#google_domains: !include 1-file-config/google_domain.yaml

################################################
## Add integrations
################################################
# zwave:
#   usb_path: /zwaveusbstick
#   network_key: !secret device_zwave_network_key

# zha:
#   usb_path: /zigbeestick
#   database_path: /config/zigbee.db
  
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

spotify: !include 1-file-config/spotify.yaml
#withings: !include 1-file-config/withings.yaml
nzbget: !include 1-file-config/nzbget.yaml
plex: !include 1-file-config/plex.yaml
python_script:
hacs: !include 1-file-config/hacs.yaml
geo_location:
  - platform: nsw_rural_fire_service_feed
    radius: 50
google: !include 1-file-config/calendar.yaml
#xiaomi_aqara: !include 1-file-config/xiaomi_aqara.yaml
homekit: !include 1-file-config/homekit.yaml
asuswrt: !include 1-file-config/asuswrt.yaml
influxdb: !include 1-file-config/influxdb.yaml
#climate: !include 1-file-config/climate_broadlink.yaml
speedtestdotnet: !include 1-file-config/speedtestdotnet.yaml
cloud:
#  google_actions: !include 1-file-config/cloud.yaml
tts: !include 1-file-config/tts.yaml
dialogflow:
#intent_script: !include 1-file-config/intent_script.yaml
ios:
  push:
    categories:  !include 1-file-config/ios_push.yaml
alarm_control_panel: !include 1-file-config/alarm.yaml
fan: !include 1-file-config/fan.yaml
logger: !include 1-file-config/logger.yaml
input_boolean: !include 1-file-config/input_boolean.yaml
input_select: !include 1-file-config/input_select.yaml
#input_number: !include 1-file-config/input_number.yaml
wemo: !include 1-file-config/wemo.yaml
#switch: !include 1-file-config/switch.yaml
camera: !include 1-file-config/aarlo_camera.yaml
aarlo: !include 1-file-config/aarlo.yaml
proximity: !include 1-file-config/proximity.yaml
vacuum: !include 1-file-config/vacuum.yaml
#hue: !include 1-file-config/light_hue.yaml
yeelight: !include 1-file-config/light_yee.yaml

################################################
## Component Includes (DIR LIST)
################################################
remote: !include_dir_list remote
switch: !include_dir_list switch
automation: !include_dir_list automation
binary_sensor: !include_dir_list binary_sensor
light: !include_dir_list light
media_player: !include_dir_list media_players
scene: !include_dir_list scene
sensor: !include_dir_list sensor
zone: !include_dir_list zone

################################################
## Component Includes (Merge Named)
################################################
group: !include_dir_merge_named group
script: !include_dir_merge_named script
