custom_header:
  !include lovelace/custom_header/custom_header.yaml

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Floorplan
background: var(--background)
views:
  - !include lovelace/5_floorplan.yaml