custom_header:
  !include lovelace/custom_header/custom_header.yaml

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: GuestMode
background: "right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%, rgba(151,177,177,1) 34%, rgba(255,255,255,1) 100%)"
views:
  - !include lovelace/8_ipad_guestmode.yaml