custom_header:
  !include lovelace/custom_header/custom_header.yaml

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml


# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
title: floorplan
background: var(--background)
views:
  - !include lovelace/5_floorplan.yaml