title: My Awesome Home

custom_header:
  compact_mode: true
  hide_config: true
  hide_raw: true
  hide_help: true
  voice_hide: true
  menu_hide: true
  button_text:
    options: '{{ time }}'
  exceptions:
  - conditions:
      user: Nicolai
      user_agent: iPad
    config:
      kiosk_mode: true
      hide_unused: true
      hide_tabs: 0,1,2,3,4,5
  - conditions:
      user_agent: Macintosh[DELETETHISPART]
    config:
      hide_tabs: 0


decluttering_templates:
  nest_picture_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_state: true
      show_icon: true
      show_name: false
      show_entity_picture: true
      entity_picture: '[[entity_picture]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
          color: black;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
  nest_icon_button:
    default:
      - size: 25%
    card:
      type: entity-button
      entity: '[[entity]]'
      name: '[[name]]'
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 1px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 30% !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }


  nest_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }

button_card_templates:
  sensor:
    color_type: icon
    show_label: true
    show_last_changed: true
    tap_action:
      action: more-info
    styles:
      name:
        - font-size: 13px
      label:
        - font-size: 10px
        - padding: 0px 5px
  
  door:
    template: sensor
    state:
      - value: 'on'
        icon: mdi:door-open
      - operator: 'default'
        icon: mdi:door
        styles:
          icon:
            - filter: opacity(50%)

  motion:
    template: sensor
    state:
      - value: 'on'
        icon: mdi:motion-sensor
      - operator: 'default'
        icon: mdi:account-search-outline
        styles:
          icon:
            - filter: opacity(50%)
  
  occupancy:
    template: sensor
    state:
      - value: 'on'
        icon: mdi:home-map-marker
      - operator: 'default'
        icon: mdi:home-outline
        styles:
          icon:
            - filter: opacity(50%) 

  fuel:
    template: sensor
    show_state: true
    show_last_changed: false

  nzb:
    template: sensor
    show_state: false
    show_last_changed: false
    state:
      - value: 'True'
        icon: mdi:download-off
      - operator: 'default'
        icon: mdi:download
        styles:
          icon:
            - filter: opacity(50%) 



# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
views:
  - !include lovelace/7_mobile_view.yaml
  - !include lovelace/2_nursery.yaml
  - !include lovelace/4_media.yaml
  - !include lovelace/3_config.yaml
  - !include lovelace/8_ipad_guestmode.yaml
  - !include lovelace/5_floorplan.yaml
  - !include lovelace/6_nest.yaml
  - !include lovelace/9_home_dash.yaml
