custom_header:
  !include lovelace/custom_header/custom_header.yaml

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml


# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
title: Our Awesome Home
background: var(--background)
views:
  - !include lovelace/7_mobile_view.yaml
  - !include lovelace/2_nursery.yaml
  - !include lovelace/4_media.yaml
  - !include lovelace/3_config.yaml
  - !include lovelace/9_home_dash.yaml
