title: My Awesome Home
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /community_plugin/plan-coordinates/plan-coordinates.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/lovelace-gap-card/gap-card.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js?v=1.1
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module


cch:
  options: clock
  voice: hide
  # exceptions:
  #   - conditions:
  #       user: Nicolai
  #       user_agent: iPad
  #     config:
  #       kiosk_mode: true
  #       hide_unused: true
  #       hide_tabs: 0,1,2,3,4,5,6


decluttering_templates:
  nest_picture_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_state: true
      show_icon: true
      show_name: false
      show_entity_picture: true
      entity_picture: '[[entity_picture]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
          color: black;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
  nest_icon_button:
    default:
      - size: 25%
    card:
      type: entity-button
      entity: '[[entity]]'
      name: '[[name]]'
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 1px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 30% !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }


  nest_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }




# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
views:

  - !include lovelace/1_home.yaml
  - !include lovelace/2_nursery.yaml
  - !include lovelace/3_config.yaml
  - !include lovelace/4_media.yaml
  - !include lovelace/5_floorplan.yaml
  - !include lovelace/6_nest.yaml
  - !include lovelace/7_home_v2.yaml
  - !include lovelace/8_ipad_guestmode.yaml
