alias: '[BEDROOM] motion - turn OFF light'
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.158_motion_bedroom
  to: 'off'
  for:
    minutes: 5
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '17:00:00'
      before: '21:30:00'
action:
  - service: light.turn_off
    data:
      entity_id: light.lifx_bedroom2
      transition: 2
