alias: "[BEDROOM] Button LONG press"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_ulli
      click_type: long_click_press
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nic
      click_type: long_click_press
mode: single
action:
  - service: fan.turn_on
    entity_id: fan.bedroom_ceiling_fan
  - delay: '00:00:02'
  - service: fan.set_speed
    entity_id: fan.bedroom_ceiling_fan
    data:
      speed: '2'
