alias: "[BEDROOM] Light On Alert"
id: bedroom_light_on_alert_id
trigger:
  platform: state
  entity_id: light.bedroom
  to: "on"
  for:
    minutes: 1
mode: single
action:
  service: notify.mobile_app_nics_iphone
  data:
    message: "The bedroom light is ON, shall I turn it off?"
    data:
      actions:
        - action: "turn_light_bedroom_off"
          title: "Turn Off Nics Bedlight"
          destructive: yes
          authenticationRequired: yes
          activationMode: "background"
