alias: "[BEDROOM] Button press"
id: bedroom_button_press_id
description: "Bedroom button actions, both nic and ulli"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_ulli
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nic
mode: single
action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.click_type == 'single' }}"
      - condition: time
        before: '23:59:00'
        after: '05:00:00'
      sequence:
        - service: light.toggle
          data:
            entity_id: light.bedroom
            transition: 2

    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.click_type == 'long_click_press' }}"
      sequence:
        - service: fan.turn_on
          entity_id: fan.bedroom_ceiling_fan
        - delay: '00:00:02'
        - service: fan.set_preset_mode
          entity_id: fan.bedroom_ceiling_fan
          data:
            speed: '2'

    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.click_type == 'double' }}"
      sequence:
        - service: fan.toggle
          entity_id: fan.bedroom_ceiling_fan
