alias: "[BEDROOM] Buttons DOUBLE press"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_ulli
      click_type: double
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nic
      click_type: double
mode: single
action:
  service: fan.toggle
  entity_id: fan.bedroom_ceiling_fan
