alias: "[BEDROOM] Button SINGLE press"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_ulli
      click_type: single
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nic
      click_type: single
mode: single
condition:
  condition: or
  conditions:
    - condition: time
      before: '23:30:00'
      after: '05:00:00'
    - condition: state
      entity_id: light.toggle
      state: 'on'
action:
  service: light.toggle
  data:
    entity_id: light.bedroom
    transition: 1
