alias: '[BEDROOM] Light On Alert'
trigger:
  platform: state
  entity_id: light.bedroom
  to: 'on'
  for:
    minutes: 20
mode: single
action:
  service: notify.mobile_app_nicsiphone 
  data:
    message: "The bedroom light is ON, shall I turn it off?"
    data:
      push:
        category: "bedroom_nic_light_duration" # Needs to match the top level identifier you used in the ios configuration
