alias: '[HALLWAY] Front Door Opens'
trigger:
  - platform: state
    entity_id: binary_sensor.door_sensor_158_entrance
    to: 'on'
condition:
  - condition: state
    entity_id: person.nic
    state: 'home'
action:
  - service: notify.ios_nicsiphone7
    data:
      message: "Front Door Opened"
