alias: '[HALLWAY] Cupboard door OPEN'
trigger:
  - platform: state
    entity_id: binary_sensor.door_sensor_158_hallway_cupboard
    to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.lifx_hallway_1
      brightness: 250
      transition: 1
