alias: '[HALLWAY] Cupboard door CLOSE'
trigger:
  platform: state
  entity_id: binary_sensor.lumi_door_hallway_cupboard
  to: 'off'
action:
  - service: light.turn_off
    entity_id: light.lifx_hallway_1
