alias: "[HALLWAY] light off timer"
id: hallway_light_off_timer_id
initial_state: true
trigger:
  platform: state
  entity_id: light.lifx_hallway_1
  to: "on"
  for:
    minutes: 10
mode: single
action:
  - service: light.turn_off
    data:
      entity_id: light.lifx_hallway_1
      transition: 2
