alias: "[HALLWAY] Front Door Opens"
id: hallway_front_door_opens_id
trigger:
  - platform: state
    entity_id: binary_sensor.xi_door_entrance
    to: "on"
mode: single
condition:
  - condition: state
    entity_id: person.nic
    state: "home"
action:
  - service: notify.mobile_app_nics_iphone
    data:
      message: "Front Door Opened"
      data:
        apns_headers:
          "apns-collapse-id": "front-door-opened"
