alias: "[HALLWAY] Doorbell press"
id: hallway_doorbell_press_id
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_doorbell
      #click_type: single
  # - platform: event
  #   event_type: xiaomi_aqara.click
  #   event_data:
  #     entity_id: binary_sensor.switch_doorbell
  #     click_type: double
mode: single
action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.click_type in ('single', 'double') }}"
      sequence:
        - service: script.turn_on
          entity_id: script.doorbell_on
# action:
#   - service: script.turn_on
#     entity_id: script.doorbell_on
