alias: "[HOME] Alarm Arm"
id: home_alarm_arm
trigger:
  - platform: state
    entity_id: binary_sensor.xi_door_entrance
    to: "off"
mode: single
condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
action:
  - wait_for_trigger:
      - platform: state
        entity_id: group.family
        to: "not_home"
    timeout: 600
    continue_on_timeout: false
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.ha_alarm
  - service: notify.mobile_app_nics_iphone
    data:
      message: 'Home Alarm ARMED {{now().strftime("%d/%m/%Y - %H:%M")}}'
