alias: '[HOME] Alarm Disarmed Off'
id: home_alarm_disarmed_off_id
trigger:
  platform: state
  entity_id: alarm_control_panel.ha_alarm
  to: 'disarmed'
mode: single
action:
  - service: script.turn_off
    entity_id: script.alarm_light_loop
  - service: script.turn_off
    entity_id: script.alarm_light_flash
  - service: notify.mobile_app_nics_iphone
    data:
      message: 'Home Alarm Disarmed {{now().strftime("%d/%m/%Y - %H:%M")}}'
