alias: '[HOME] Disarm When Home'

id: home_disarm_when_home
trigger:
  - platform: state
    entity_id: person.nic
    to: 'home'
  - platform: state
    entity_id: person.ulli
    to: 'home'
mode: single
action:
  service: alarm_control_panel.alarm_disarm
  entity_id: alarm_control_panel.ha_alarm
