alias: '[HOME] Trigger Alarm'
id: home_trigger_alarm_id
trigger:
  - platform: state
    entity_id: binary_sensor.xi_door_entrance
    to: 'on'
  - platform: state
    entity_id:  binary_sensor.158_door_balcony
    to: 'on'
  - platform: state
    entity_id: group.motion_sensors
    to: 'on'
mode: single
condition:
  condition: state
  entity_id: alarm_control_panel.ha_alarm
  state: armed_away
action:
  service: alarm_control_panel.alarm_trigger
  entity_id: alarm_control_panel.ha_alarm
