alias: '[HOME] Alarm Arm'
trigger:
  - platform: state
    entity_id: person.nic
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: person.ulli
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: device_tracker.nicsiphone7
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.ullisiphone
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.ha_alarm
  - service: notify.ios_nicsiphone7
    data:
      message: 'Home Alarm ARMED {{now().strftime("%d/%m/%Y - %H:%M")}}'
