alias: "[HOME] Ulli is Home"
id: home_ulli_is_home_id
trigger:
  platform: state
  entity_id: person.ulli
  from: "not_home"
  to: "home"
mode: single
action:
  service: notify.mobile_app_nics_iphone
  data:
    message: "Ulli is home!"
    data:
      apns_headers:
        "apns-collapse-id": "ulli-home"
