alias: "[HOME] Ulli is Home"
trigger:
  platform: state
  entity_id: person.ulli
  from: "not_home"
  to: "home"
mode: single
action:
  service: notify.mobile_app_nicsiphone
  data:
    message: "Ulli is home!"
