alias: '[HOME] Turn ON Light when first person comes home after sunset'
id: home_turn_on_light_when_first_person_home_id
trigger:
  - platform: state
    entity_id: person.nic
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: person.ulli
    from: 'not_home'
    to: 'home'
mode: single
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
    - condition: time
      after: '16:00:00'
      before: '22:00:00'
    - condition: template
      value_template: "{% if not is_state('media_player.apple_tv_2', 'playing') %}true{% endif %}"
action:
  service: script.turn_on
  entity_id: script.home_after_dark