alias: "[HOME] Ulli is Home"
trigger:
  platform: state
  entity_id: device_tracker.ullisiphone
  from: "not_home"
  to: "home"
action:
  service: notify.mobile_app_nicsiphone
  data:
    message: "Ulli is home!"
