alias: '[HOME] Turn on Bibop (Mon Fri)'
id: home_turn_on_bibop_id
trigger:
  platform: time
  at: "10:00:00"
mode: single
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - fri
    - condition: state
      entity_id: person.nic
      state: 'not_home'
    - condition: state
      entity_id: person.ulli
      state: 'not_home'
action:
  - service: vacuum.start
    entity_id: vacuum.bibop
  - service: notify.mobile_app_nics_iphone
    data:
      message: "BiBop was put to action"
      data:
        actions:
        - action: "bibop_return_home"
          title: "Go Home Bibop"
          destructive: yes
          authenticationRequired: yes
          activationMode: "background"
