alias: '[HOME] Turn off home when nobody home' 
trigger:
  - platform: state
    entity_id: person.nic
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: state
    entity_id: person.ulli
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
mode: single
condition:
  condition: and
  conditions:
    - condition: time
      before: '19:00:00'
      after: '07:00:00'
    - condition: state
      entity_id: person.nic
      state: 'not_home'
    - condition: state
      entity_id: person.ulli
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: climate.daikin
          state: 'on'
        - condition: state
          entity_id: group.all_lights
          state: 'on'
        - condition: state
          entity_id: switch.media_unit
          state: 'on'
        - condition: state
          entity_id: switch.espresso
          state: 'on'
action:
  - service: script.turn_on
    entity_id: script.turn_home_off_timer
