alias: '[HOME] Google Home DAY Volume'
trigger:
  platform: time
  at: '07:00:00'
action:
  - service: media_player.volume_set
    entity_id: media_player.living_room_home
    data:
      volume_level: 0.25
  - service: media_player.volume_set
    entity_id: media_player.entryway_speaker
    data:
      volume_level: 0.35
  - service: media_player.volume_set
    entity_id: media_player.googlehome5332
    data:
      volume_level: 0.3
  - service: media_player.volume_set
    entity_id: media_player.googlehome9051
    data:
      volume_level: 0.3
