alias: '[HOME] Turn on Bibop (Mon Fri)'
trigger:
  platform: time
  at: "10:00:00"
mode: single
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - fri
    - condition: state
      entity_id: person.nic
      state: 'not_home'
    - condition: state
      entity_id: person.ulli
      state: 'not_home'
action:
  - service: vacuum.start
    entity_id: vacuum.bibop
  - service: notify.mobile_app_nicsiphone
    data:
      message: "BiBop was put to action"
      data:
        push:
          category: "bibop_started" # Needs to match the top level identifier you used in the ios configuration
