alias: '[HOME] Turn OFF vacation mode when home'
trigger:
  - platform: state
    entity_id: person.nic
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: person.ulli
    from: 'not_home'
    to: 'home'
mode: single
condition:
  - condition: state
    entity_id: input_boolean.on_holiday
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.on_holiday
  - service: notify.all_ios
    data:
      message: 'Welcome Home! Hope you had a great vacation! Turning off holiday mode at {{now().strftime("%H:%M")}}'
