# Send an iOS notification when the ESPRESSO MACHINE is on for longer than 90 min
alias: '[IOS] espresso_off'
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: turn_espresso_off
action:
  service: switch.turn_off
  entity_id: switch.espresso