alias: '[KITCHEN] Espresso Machine ON'
description: "Turns on Espresso machine"
initial_state: True
trigger:
  #weekdays
  - platform: time
    at: '07:00:00'
  #Weekends
  - platform: time
    at: '07:30:00'
mode: single
action:
  - choose:
    #Weekdays, auto turn off
    - conditions:
      - condition: time
        after: '07:15:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
      - condition: state
        entity_id: input_boolean.on_holiday
        state: 'off'
      sequence:
        - service: switch.turn_on
          entity_id: switch.espresso
    
    #WeekDAYS, auto turn off
    - conditions:
      - condition: time
        before: '07:15:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: input_boolean.on_holiday
        state: 'off'
      sequence:
        - service: switch.turn_on
          entity_id: switch.espresso

