alias: '[KITCHEN] Espresso Machine ON Weekends'
initial_state: True
trigger:
  platform: time
  at: '07:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.on_holiday
    state: 'off'
action:
  service: switch.turn_on
  entity_id: switch.espresso
