alias: '[KITCHEN] dim OFF'
trigger:
  - platform: state
    entity_id: binary_sensor.wall_switch_left_158_kitchen
    from: 'on'
    to: 'off'
  # - platform: state
  #   entity_id: binary_sensor.switch_158_button_nic
  #   from: 'on'
  #   to: 'off'
mode: queued
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.kitchen_dim
    state: 'on'
  - condition: state
    entity_id: light.kitchen_lights
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_dim
