alias: '[KITCHEN] Espresso on for 30m notification' 
initial_state: True
trigger:
  platform: state
  entity_id: switch.espresso
  to: 'on'
  for:
    minutes: 30
mode: single
action:
  - service_template: >-
      {% if is_state("person.nic", "home") and
            is_state("person.ulli", "home") %}
      notify.all_ios
      {% elif is_state("person.nic", "home") %}
      mobile_app_nicsiphone
      {% else %}
      notify.mobile_app_ulli_s_iphonese
      {% endif %}
    data:
      message: 'Mr Espresso is ready for you here at {{now().strftime("%H:%M")}}'
  
 