alias: '[KITCHEN] disable kitchen override boolean when lights off'
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.kitchen_lights
  to: 'off'
  for:
    minutes: 1
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_light_override
