alias: '[KITCHEN] light brighten'
initial_state: 'on'
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158_kitchen
      click_type: single
mode: queued
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.kitchen_light_override
  - service: light.turn_on
    data: 
      entity_id: light.kitchen_lights
      transition: 0.5
      brightness_step_pct: 10
 