alias: '[KITCHEN] Espresso on for 30m notification'
initial_state: True
trigger:
  platform: state
  entity_id: switch.espresso
  to: 'on'
  for:
    minutes: 30
action:
  - service: notify.all_ios
    data:
      message: 'Espresso is ready {{now().strftime("%H:%M:%S")}}'
  - service: scene.create
    data:
      scene_id: espresso_30min
      snapshot_entities: 
        - light.led_shelf
  - service: lifx.set_state
    data:
      entity_id: light.led_shelf
      color_name: green
      power: false
      brightness: 60
  - service: lifx.effect_pulse #TODO: Update this to LED now
    data:
      entity_id: light.led_shelf
      color_name: green
      mode: blink
      cycles: 5
      brightness: 60
  - service: scene.turn_on
    data:
      entity_id: scene.espresso_30min
  
 