alias: '[KITCHEN] dishwasher toggle'
initial_state: 'on'
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158_kitchen
      click_type: double
action:
  - service: switch.toggle
    entity_id: switch.dishwasher