alias: '[KITCHEN] lights OFF'
initial_state: 'on'
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158_kitchen
      click_type: both
mode: queued
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_light_override
  - service: light.turn_off
    data:
      entity_id: light.kitchen_lights
      transition: 1
