alias: '[KITCHEN] Espresso on for 30m notification' 
id: kitchen_espresso_on_for_30m_notification_id
initial_state: true
trigger:
  platform: state
  entity_id: switch.espresso
  to: 'on'
  for:
    minutes: 30
mode: single
action:
  - service: >-
      {% if is_state("person.nic", "home") and
            is_state("person.ulli", "home") %}
      notify.all_ios
      {% elif is_state("person.nic", "home") %}
      notify.mobile_app_nics_iphone
      {% else %}
      notify.mobile_app_ulli_s_iphonese
      {% endif %}
    data:
      message: 'Mr Espresso is ready for you here at {{now().strftime("%H:%M")}}'
      data:
        apns_headers:
          'apns-collapse-id': 'espresso-ready'
  
 