alias: "[KITCHEN] Espresso On Alert"
id: kitchen_espresso_on_alert_id
trigger:
  platform: state
  entity_id: switch.espresso
  to: "on"
  for:
    hours: 1
    minutes: 30
mode: single
action:
  service: notify.mobile_app_nics_iphone
  data:
    message: "Espresso Machine has been on for more than 90 min. !"
    data:
      apns_headers:
        "apns-collapse-id": "espresso-off"
      actions:
        - action: "turn_espresso_off"
          title: "Turn Espresso Machine Off"
          destructive: yes
          authenticationRequired: yes
          activationMode: "background"
