alias: '[KITCHEN] dim ON'
initial_state: 'on'
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158_kitchen
      click_type: long_click_press
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nic
      click_type: long_click_press
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.kitchen_dim
    state: 'on'
  - condition: state
    entity_id: light.kitchen_lights
    state: 'on'
action:
  - service: script.turn_on
    entity_id: script.dim_light_kitchen
