alias: "[KITCHEN] motion - turn ON light"
id: kitchen_motion_turn_on_light_id
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158_kitchen
  to: "on"
mode: queued
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.led
      state: "off"
    - condition: time
      after: "05:30:00"
      before: "23:00:00"
    - condition: state
      entity_id: input_boolean.kitchen_light_override
      state: "off"
action:
  service: scene.turn_on
  data:
    entity_id: >
      {% if is_state('binary_sensor.morning', 'on') %}
        scene.kitchen_morning_light
      {% elif is_state('binary_sensor.evening', 'on') %}
        scene.kitchen_evening_light
      {% elif is_state('binary_sensor.night', 'on') %}
        scene.kitchen_night_light
      {% else %}
        scene.kitchen_daytime_light
      {% endif %}
