alias: '[LAUNDRY] door light off timer'
trigger:
  - platform: state
    entity_id: binary_sensor.lumi_door_laundry
    to: 'on'
    for:
      minutes: 2
condition:
  - condition: state
    entity_id: binary_sensor.lumi_motion_laundry
    state: 'off'
action:
  - service: light.turn_off
    entity_id: light.lifx_laundry
