alias: '[LAUNDRY] motion light off timer'
trigger:
  - platform: state
    entity_id: binary_sensor.158_motion_laundry
    to: 'off'
    for:
      minutes: 2
mode: queued
action:
  - service: light.turn_off
    entity_id: light.lifx_laundry
