alias: '[LAUNDRY] door closes'
id: laundry_door_closes_id
trigger:
  platform: state
  entity_id: binary_sensor.158_door_laundry
  to: 'off'
mode: queued
action:
  - service: light.turn_off
    entity_id: light.lifx_laundry
