alias: '[LAUNDRY] door light off timer'
id: laundry_door_light_off_timer_id
trigger:
  - platform: state
    entity_id: binary_sensor.158_door_laundry
    to: 'on'
    for:
      minutes: 2
mode: queued
condition:
  - condition: state
    entity_id: binary_sensor.158_motion_laundry
    state: 'off'
action:
  - service: light.turn_off
    entity_id: light.lifx_laundry
