alias: '[LAUNDRY] door opens or motion'
trigger:
  - platform: state
    entity_id: binary_sensor.158_motion_laundry
    to: 'on'
  - platform: state
    entity_id: binary_sensor.158_door_laundry
    to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.lifx_laundry
      brightness: 250
      transition: 1
