alias: "[LAUNDRY] Water Leak ALARM laundry"
id: laundry_water_leak_alarm_laundry_id
trigger:
  platform: state
  entity_id: binary_sensor.water_leak_sensor_158_laundry
  to: "on"
mode: queued
action:
  - service: notify.all_ios
    data:
      message: 'LAUNDRY WATER LEAK ALARM TRIGGERED {{now().strftime("%Y%m%d-%H%M%S")}}'
      title: "CRITICAL"
      data:
        attachment:
          url: !secret water_leak_alarm_picture_url
          content-type: png
          hide-thumbnail: false
  - service: light.turn_on
    entity_id:
      - light.bedroom_ceiling
      - light.lifx_hallway_1
    data:
      brightness: 250
      color_name: red
