alias: '[LIVINGROOM] motion - turn OFF if nobody around'
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.158_motion_livingroom
  to: 'off'
  for:
    minutes: 30
mode: single
condition:
  condition: and
  conditions:
    - condition: time
      after: '05:00:00'
      before: '21:00:00'
    - condition: template
      value_template: "{{ not is_state('climate.daikin', 'off') }}"
action:
  - service: climate.turn_off
    entity_id: climate.daikin
