alias: "[LIVINGROOM] Paused/Stopped Movie"
trigger:
  - platform: state
    entity_id: media_player.apple_tv_livingroom
    from: 'playing'
    to: 'paused'
  - platform: state
    entity_id: media_player.apple_tv
    from: 'playing'
    to: 'paused'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.tv_movie_lights
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.normal_lighting
