alias: "[LIVINGROOM] Turn on light when sun sets and home"
trigger:
  platform: sun
  event: sunset
  offset: "-00:20:00"
condition:
  - condition: state
    entity_id: group.all_devices
    state: home
action:
  service: light.turn_on
  entity_id: group.livingroom_lamps