alias: "[LIVINGROOM] turn off heater if balcony open"
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.158_door_balcony
  to: "on"
  for:
    seconds: 20
mode: single
condition:
  - condition: template
    value_template: "{% if not is_state('climate.daikin', 'off') %}true{% endif %}"
action:
  - service: climate.turn_off
    entity_id: climate.daikin
  - service: >-
      {% if is_state("person.nic", "home") and
            is_state("person.ulli", "home") %}
      notify.all_ios
      {% elif is_state("person.ulli", "home") %}
      notify.mobile_app_ulli_s_iphone 
      {% else %}
      notify.mobile_app_nicsiphone
      {% endif %}
    data:
      message: "Balcony door opened, so I turned off the AC :) (Go Nature!) "
