alias: '[LIVINGROOM] motion - turn ON Heater'
id: livingroom_motion_turn_on_heater_id
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.158_motion_livingroom
  to: 'on'
mode: single
condition:
  - condition: state
    entity_id: binary_sensor.158_door_balcony
    state: 'off'
  - condition: state
    entity_id: climate.daikin
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.158_temperature_livingroom
    below: 21
  - condition: time
    after: '06:00:00'
    before: '22:00:00'
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.daikin
      hvac_mode: "heat"
