alias: '[LIVINGROOM] turn off heater if balcony open'
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.lumi_door_livingroom_balcony
  to: 'on'
  for:
    seconds: 20
condition:
  - condition: template
    value_template: "{% if not is_state('climate.livingroom_ac', 'off') %}true{% endif %}"
  #- condition: state
  #  entity_id: climate.livingroom_ac
  #  state: 'on'
    #for:
    #  minutes: 1
action:
  - service: climate.turn_off
    entity_id: climate.livingroom_ac
  - service_template: >-
      {% if is_state("person.nic", "home") and
            is_state("person.ulli", "home") %}
      notify.all_ios
      {% elif is_state("person.ulli", "home") %}
      notify.ullisiphone
      {% else %}
      notify.ios_nicsiphone7
      {% endif %}
    data:
      message: "Balcony door opened, so I turned off the AC :) (Go Nature!) "