alias: "[NURSERY] Ceiling Light toggle"
id: nursery_ceiling_light_toggle_id
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nursery
      click_type: long_click_press
mode: single
action:
  - service: light.toggle
    data:
      entity_id: 
        - light.lifx_nursery_1
        - light.lifx_nursery_2
      transition: 3
