alias: '[NURSERY] door OPEN at night'
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.door_sensor_158_nursery
  to: 'on'
mode: queued
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '18:00:00'
      #before: '21:00:00'
    - condition: state
      entity_id: light.nursery_ceiling
      state: 'off'
action:
    - service: scene.create
      data:
        scene_id: nursery_door
        snapshot_entities: 
          - light.lifx_dining1
          - light.lifx_livingroom1
          - light.lifx_dining2
          - light.lifx_livingroom2
          - light.lifx_kitchen2
          - light.lifx_kitchen1
          - light.lifx_hallway_1
          - light.lifx_laundry
          - light.led
          - light.led_shelf
          - light.tv
          - light.lifx_bedroom1
          - light.lifx_bedroom2
          - light.lifx_bedroom_desk
          - light.desk
          - media_player.denon_amp
          - media_player.apple_tv
    - service: light.turn_off
      entity_id:
        - light.lifx_dining1
        - light.lifx_livingroom1
        - light.lifx_dining2
        - light.lifx_livingroom2
        - light.lifx_kitchen2
        - light.lifx_kitchen1
        - light.lifx_hallway_1
        - light.lifx_laundry
        - light.led
        - light.led_shelf
        - light.tv
        - light.lifx_bedroom1
        - light.lifx_bedroom2
        - light.lifx_bedroom_desk
        - light.desk
    - condition: state
      entity_id: switch.media_unit
      state: 'on'
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_amp
        source: "DVD"
    - condition: state
      entity_id: media_player.apple_tv
      state: 'playing'
    - service: media_player.media_pause
      entity_id: media_player.apple_tv
