alias: "[NURSERY] Winefridge Off at night"
initial_state: True
trigger:
  platform: time
  at: "21:15:00"
condition:
  - condition: state
    entity_id: input_boolean.winefridge_off_night
    state: 'on'
action:
  service: homeassistant.turn_off
  entity_id: switch.plug_158d0002168ad1
