alias: '[NURSERY] reset light override light menu'
id: nursery_reset_light_override_light_menu_id
initial_state: true
trigger:
  platform: state
  entity_id: input_boolean.nursery_sleeping_override
  to: 'on'
  for:
    seconds: 5
mode: single
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nursery_sleeping_override
