alias: "[NURSERY] Ceiling Light toggle"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nursery
      click_type: long_click_press
action:
  # - service: lifx.set_state
  #   data:
  #     entity_id: light.lifx_nursery_1
  #     white_value: 255
  #     brightness: 1
  - service: light.toggle
    data:
      entity_id: light.lifx_nursery_1
      transition: 3
