alias: "[NURSERY] Winefridge ON in Morning"
initial_state: True
trigger:
  platform: time
  at: "09:00:00"
condition:
  - condition: state
    entity_id: input_boolean.winefridge_off_night
    state: 'on'
action:
  service: homeassistant.turn_on
  entity_id: switch.plug_158d0002168ad1
