alias: "[NURSERY] Ceiling Light toggle"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      unique_id: 00:15:8d:00:02:55:6c:9c:1:0x0006
      command: click
      args:
        click_type: single
      #entity_id: binary_sensor.switch_158_button_nursery
      #click_type: long_click_press
action:
  - service: light.lifx_set_state
    data:
      entity_id: light.lifx_nursery_1
      white_value: 255
      brightness: 1
  - service: light.toggle
    data:
      entity_id: light.lifx_nursery_1
      transition: 1
