alias: "[NURSERY] Night Light on"
id: nursery_night_light_on_id
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nursery
      click_type: single
mode: single
action:
  - service: scene.turn_on
    data:
      entity_id: scene.nursery_night_read
