alias: "[NURSERY] Floorlamp button toggle"
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158_button_nursery
      click_type: double
action:
  - service: light.toggle
    data:
      entity_id: light.livingroom
      transition: 3
